---
default_install_hook_types:
  - pre-commit
  - commit-msg
  - pre-push
  - post-commit

default_stages:
  - commit
  - push
  - commit-msg

repos:
  # * ================================== Formatters ==================================
  # * Black hook
  - repo: local
    hooks:
      - id: black
        name: Black formatter
        entry: black
        language: system
        types: [python]

  # * ================================== Testing ==================================

  # * Pytest with coverage
  - repo: local
    hooks:
      - id: pytest-coverage
        name: Pytest with coverage
        entry: pytest
        language: system
        pass_filenames: false
